# Generated by Django 2.1.2 on 2018-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('total_job_wages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_federal_wages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemized_deduction_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal_taxable_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_federal_tax_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_federal_payments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_taxable_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_state_tax_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_state_payments', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
