# Generated by Django 2.1.2 on 2018-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('account', models.CharField(choices=[('Robinhood', 'Robinhood'), ('Tastyworks', 'Tastyworks')], default='Robinhood', max_length=30)),
                ('position_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('position_open_date', models.DateField()),
                ('position_expiration_date', models.DateField()),
                ('position_close_date', models.DateField()),
                ('option_play', models.CharField(choices=[('Naked Call', 'Naked Call'), ('Naked Put', 'Naked Put'), ('Call Credit Spread', 'Call Credit Spread'), ('Call Debit Spread', 'Call Debit Spread'), ('Put Credit Spread', 'Put Credit Spread'), ('Put Debit Spread', 'Put Debit Spread'), ('Iron Condor', 'Iron Condor'), ('Iron Butterfly', 'Iron Butterfly'), ('Calendar Spread', 'Calendar Spread'), ('Jade Lizard', 'Jade Lizard'), ('Put Ratio Backspread', 'Put Ratio Backspread'), ('Synthetic Covered Call', 'Synthetic Covered Call'), ('Custom', 'Custom')], default='Naked Call', max_length=50)),
                ('strike_prices', models.CharField(max_length=100)),
                ('directional_bias', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], default='Bullish', max_length=20)),
                ('contracts_bought', models.DecimalField(decimal_places=0, max_digits=6)),
                ('strategy', models.CharField(choices=[('Sell Premium', 'Sell Premium'), ('Trend Trade', 'Trend Trade'), ('Spec Trade', 'Spec Trade'), ('Quick Trade', 'Quick Trade'), ('Flat Trade', 'Flat Trade'), ('Earnings Play', 'Earnings Play')], max_length=50)),
                ('probability_of_profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buying_power_reduction', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_to_enter_trade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees_to_enter_trade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_to_exit_trade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees_to_exit_trade', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
