# Generated by Django 2.1.2 on 2018-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionposition',
            name='cost_to_exit_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='fees_to_exit_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='position_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
