# Generated by Django 2.0.5 on 2018-05-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope', models.IntegerField()),
                ('par', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holesplayed', models.IntegerField(default=18)),
                ('date', models.DateField(unique=True)),
                ('strokes', models.IntegerField()),
                ('putts', models.IntegerField()),
                ('fairways_hit', models.IntegerField()),
                ('gir', models.IntegerField()),
                ('equistrokes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Golf.Course', to_field='course')),
            ],
        ),
    ]
